# Generated by Django 3.2.14 on 2022-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
