# Generated by Django 4.0.1 on 2022-09-25 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_filesupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('FoodT', models.CharField(max_length=122)),
                ('FoodQ', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('phone', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'DonateNows',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nid', models.IntegerField()),
                ('vemail', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=122)),
                ('vaddress', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=50)),
                ('describe', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Vlunteers',
            },
        ),
    ]
